### ISSUE TITLE
5.0.5.3 Bittrex API sending wrong data?

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/Gunthy#11]
I set "GUNTHY_API": false on all pairs.
Nothing else very fancy in the config.js

I noticed:
* gunbot didn't make ANY trade for a night (while it usually does 10/20)
* the displayed numbers are completely crazy, see picture below

See the below prices for this pair (price to buy is 20 times the current price ???)

![2017-10-01 17_00_37-k__gunbot_gunthy_v5053_fb1f9db_win_lin_gunthy exe](https://user-images.githubusercontent.com/32078594/31055949-14506990-a6cb-11e7-9c6e-0ad580cef462.png)

Config stepgain:

			"PERIOD": 15,
			"BUY_LEVEL": 3,
			"GAIN": 0.75,
			"EMA1": 16,
			"EMA2": 8,
			"HIGH_BB": 50,
			"LOW_BB": 25,
			"STDV": 2,
			"SMAPERIOD": 50,
			"BUYLVL1": 3,
			"BUYLVL2": 5,
			"BUYLVL3": 9,
			"SELLLVL1": 0.85,
			"SELLLVL2": 1.5,
			"SELLLVL3": 5,
			"BUYLVL": 1,
			"SELLLVL": 1,
			"LASTPOINTS": 5,
			"AVGPOINTS": 250,
			"AVGMINIMUM": 0.00000001,
			"GUNTHY_API": false,
			"PP_BUY": 0.00000001,
			"PP_SELL": 0.12345678,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 99,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.0005,
			"MIN_VOLUME_TO_SELL": 0.0005

See also this screenshot, am I tired or I don't understand any of those prices ?

![2017-10-01 16_51_45-k__gunbot_gunthy_v5053_fb1f9db_win_lin_gunthy exe](https://user-images.githubusercontent.com/32078594/31056031-eb6d7c60-a6cb-11e7-8cc9-3c5d9e1101c5.png)

Reminder I didn't use gunbot history server (I set "GUNTHY_API": false on all pairs.)

**Comment by GuntharDeNiro** [comment]
@paramecie fixed: 5054 coming in a few

**Comment by flanagansteve** [comment]
I also get crazy API prices sometimes, like this JSON response:

`
ETH-XMR:	{"success":true,"message":"","result":{"Bid":16780.00000000,"Ask":16859.99999998,"Last":16780.00000000}}`

or this:

`
ETH-LTC:	{"success":true,"message":"","result":{"Bid":16850.01000000,"Ask":16890.00000002,"Last":16850.01000000}}`

I also sometimes get a response for the XMR-ETH market (which I shouldn't, the API should only respond to the ETH-XMR market request) and get the same prices rather than the reciprocals:

`
XMR-ETH:	{"success":true,"message":"","result":{"Bid":16855.00000000,"Ask":16865.00000001,"Last":16855.00000000}}`

no idea why this stuff is happening. Unreliable APIs scare me, what if the bot I'm coding executed a trade based on this info?
