### ISSUE TITLE
5.0.5.5 Bot stops functioning 

### ISSUE THREAD

**Issue by svenberghuis** [GuntharDeNiro/Gunthy#17]
I'm running 40 pairs, each in a separate instance. The problem I have instances just stop functioning after a while. Closing the bot and restarting it makes it work for a while.

It looks like the problem starts after it initiates a new cycle or after the EMA1/EMA2 line, see screenshot.

![gb](https://user-images.githubusercontent.com/32439383/31126131-07212c24-a84b-11e7-9891-a03cc827a573.png)

**Comment by paramecie** [comment]
Is it like this? #7

**Comment by paramecie** [comment]
Note: if you use gunthy_api=true, then due to the fact you use 40 instances of gunthy, you end up sending 2, 5 up to 40 queries *simultaneously* to gunthy server.

That's not "fair", and may be one reason the server is overloaded and doesn't reply for others.
Just my 2 cents, and trying to understand...

**Comment by svenberghuis** [comment]
No, doesn't look like #7, I don't receive any error. It just stops working without any error.
I don't use the gunthy_api

**Comment by paramecie** [comment]
OK, thank you!

But I don't receive any error, see my original post:
https://github.com/GuntharDeNiro/BTCT/issues/156

**Comment by svenberghuis** [comment]
Indeed, same as #156, didn't saw that one. 

Sometimes it hangs at the EMA1/EMA2 line, sometimes just before that.

**Comment by paramecie** [comment]
OK!

But maybe it's still a problem on gunthy servers.

I guess the bot is checking your licence from time to time (not only when starting). Then, with 40 instances, sending too much simultaneous request (along with other users) you just get rejected or ignored by the licence server.
And maybe the bot is waiting for a reply like "valid" or "invalid" - but receiving nothing isn't implemented... then it hangs...

**Comment by svenberghuis** [comment]
I'm not saying that's the case, but if that would be the case then there should be something build in that once the bot starts and the license is validated the bot should be able to run at least for 48 hours without a connection to the license server. It's ok for the bot to check in every x minutes at the license server but in case the license server is unavailable or just to busy to respond within the specified timeout the bot must be able to continue.

The biggest advantage of the bot is to have it run 24/7 without interuptions.

**Comment by thejeremywhite** [comment]
Same issue with 505.5, but I am running one instance with 15 pairs. It will run for about an hour and then hang

**Comment by svenberghuis** [comment]
Having more instances will just make the problem appear sooner. With 40 instances about once every 10 minutes.

**Comment by Utone** [comment]
I just noticed this in the GUI as well:
[img]https://ptpimg.me/oorp6t.png[/img]

This is seriously fucked, now im beginning to understand why even on 5.0.4  I found some pairs that didn't debag.. Which version before this Doesn't have this as far as you guys know?

**Comment by paramecie** [comment]
For "debagging" I personnaly do it manually: it's not worse making a bot for this, IMO.
Simply place a sell order and forget it.

I had hang problems (freezing) with 5.0.4 I think, I reported it.
One thing is sure, since I use gunthy_api = false, I have had no freeze.

Also tweak the BOT_DELAY, right now I use bot_delay=15, but I went up to 50+ to avoid the marketplace burning me...

**Comment by paramecie** [comment]
I worked/tried to understand this boot 7/24 for a few weeks.

Right now, what I'm sure of:

3.3.2 is the only stable/reliable version. Problem, it often (or too much) double buy (with double_up=false). That's its MAIN problem for me. AND it takes ages to run it if you close it (as if you run it automatically, you end up making batches of bunches of requests on your marketplace, so I run each pair, one by one). It kills you.

4.x version seems to have problems, and is probably abandonned.

5.x is NOT ready. Just the cycle problem: I took an hour this afternoon to understand why a single pair had to wait 7 minutes to be refreshed (while others were refreshed 2 or 3 times...) At 15:46, it missed a price where it could buy because some pairs are refreshed, again, 5 to 10 minutes later (10 minutes!) :-(

With the hangs, the various errors others and I reported (including in the config), I'm worried they can build a stable version.
Who cares of "TV" or the GUI features when right now, without even a GUI it hangs, can't use gunthy_api, or doesn't refresh pairs?

They also need a minimum doc, or references to various posts - people in forum ask "how do I start the bot?".

Please please Gunthar and Team, make us a reliable version, the one that puts 3.3.2 to the garbage, so people aren't obliged to give up and end up running 3.3.2 again, and again, because nothing else works.

A *million* thanks.

**Comment by utdrmac** [comment]
5055 stopped working here too.

**Comment by jkomar** [comment]
If anyone is looking for a workaround to have the frozen bot start moving again, I found that if there is a config file change detected, it will reload the config and recover from the frozen state.

I set a cron job to do:

`touch -c /path/to/gunbot/config.js`

every few minutes to update the time stamp on the config file. That way I don't have to keep checking to make sure my bot is not frozen up.

Not an elegant solution, but it's working for me while we wait for a fix.

Jason

**Comment by GuntharDeNiro** [comment]
@jkomar question: are you running multiple exchanges in a single instance?

**Comment by jkomar** [comment]
@GuntharDeNiro Yes. Poloniex and Bittrex.

**Comment by GuntharDeNiro** [comment]
@jkomar ok can you try using one single exchange for each instance and report back if it hangs again, please? Thanks!

**Comment by jkomar** [comment]
@GuntharDeNiro Will do. Thanks!
