### ISSUE TITLE
Empty response from exchange

### ISSUE THREAD

**Issue by oefterdal** [GuntharDeNiro/Gunthy#2]
I get this in stdout:

------------------------------------------------------------------------------------------------

stdout: HIGH BB: 0.00000000 == SMA: 0.00000000 == LOW BB: 0.00000000
------------------------------------------------------------------------------------------------

stdout: Empty response from exchange...retrying again...

stdout: ------------------------------------------------------------------------------------------------
 ɢՍΠɃøŦ v5.0.5  Scanning bittrex for trading opportunities 2017/09/29 12:58:43
------------------------------------------------------------------------------------------------

stdout: 2017/09/29 12:58:43: BTC-XST Last Bid/Ask 0.00005413/0.00005494

stdout: 2017/09/29 12:58:49: Got Trading History

stdout: 2017/09/29 12:58:49: Price to buy: 0.00000000

stdout: 2017/09/29 12:58:53: Got Open Orders

stdout: 2017/09/29 12:58:53: Last Bid/Price to sell: 0.00005413/0.00005202
2017/09/29 12:58:53: Last Ask/Price to buy: 0.00005494/0.00000000

**Comment by Gnorbe** [comment]
I confirm the problem with Gunbot 5.0.5 and Bittrex.
![immagine](https://user-images.githubusercontent.com/31937016/31037460-3b5a7ac2-a571-11e7-8125-0972f2dfc14d.jpg)

Sometimes the problem is for all couples, sometimes only for some. The problem seems random but frequent. With the previous version 5.0.4, run at the same time as 5.0.5, the problem is not present. However i was noticed that version 5.0.4 did not log this type of error.  The configuration file is correct and all variables are present.

**Comment by Tradingisfun17** [comment]
i saw this one and it is inconsistent

**Comment by BotticelliAngel** [comment]
Guys, I think I worked out what might be happening here. I had nAffie help me confirm my GB v5.0.5 config settings. Here's some defect recreation info:

** System: Windows 10, x64 running GB v5.0.5 with GUI.

Step 1: To recreate this issue, use a fresh version of GB (as at 30/09/2017) with all default settings. Within the configuration, create a Bittrex exchange entry and add a BTC-AEON pair and a BTC-ETH pair using BB strategy. Save and run.

Step 2: Observe the console window and notice that BTC-ETH works fine, but BTC-AEON does not with the "Empty response from exchange...retrying again..." message appearing for BTC-AEON.

Step 3: While GB is running, change the BTC-AEON coin pair to STEPGAIN strategy. Save.

Step 4: Observe the console window and notice that BTC-AEON is now trading, with no more error messages.

After speaking to a few individuals, we share the common idea that there isn't enough data on the gunthar servers(?) for BB calculations and hence the error message we see in the console window.

For now, I am using STEPGAIN strategy and there's no more error messages.

I hope this helps someone!

**Comment by Gnorbe** [comment]
Yes, with stepgain the problem "Empty response from exchange...retrying again" disappears. If it was a Bittrex problem, something would not work with either stepgain or pure BB with version 5.0.4. Probably, as has been hypothesized by @BotticelliAngel, sometimes there are problems getting BS values from the gunbot server.

**Comment by Tradingisfun17** [comment]
i change to stepgain and the error disappear. Now looking for some info about Stepgain? any can explain or point me the direction where can i find the details explanation of all strategies?

**Comment by Gnorbe** [comment]
With 5.0.5.2 and 5.0.5.23 versions the problem seems to be getting worse. Now I get the error "Empty response from exchange ... retrying again ..." continuously for all the pair. As mentioned above, the problem occurs with the BB strategy, using stepgain the error disappears. The bot with BB strategy is unusable for me.

The configuration file is correct and contains all the variables. I just changed "WATCH_MODE": true and "BUY_ENABLED": false, to test the bot.

The config.js file I'm using:  https://pastebin.com/AWqb8wE3
Console Log: https://pastebin.com/4yD5WApC

Tested with: Amazon VPS and Contabo VPS with Windows 2012 server.

**Comment by Gnorbe** [comment]
Add some information to help solve the problem. if i start the bot with "GUNTHY_API": false in bb strategy, i get the error occasionally. If I change to "GUNTHY_API": true i get the error continuously. It's quite obvious that using Gunthy API for some reason aggravates the "Empty response from exchange" problem.

**Comment by ebplista** [comment]
Hi There.
I see those errors in BB. dont know if they appear when you are changing between strategies.
but after i restarted gunbot for the pair with bb and this error message, it worked again.
(Linux, GB 5.0.55)

**Comment by Utone** [comment]
Not here, can not shake this.
Going to try GAIN

**Comment by vivrelib** [comment]
i have this problem with several traidingpairs and poloniex with Gunthy_v5055_RC_8ab53b2
