### ISSUE TITLE
V505-95572df takes 18-20 seconds to retrieve trading history for trading pair

### ISSUE THREAD

**Issue by rhessing** [GuntharDeNiro/Gunthy#5]
Please see this pastebin: https://pastebin.com/1sBqb1Yd

On V5.0.4. these issues are not existent (1 second to load trading history).

**Comment by rhessing** [comment]
To see the difference between 5.0.4 and 5.0.5 please see this pastebin from the logs from version 5.0.4: https://pastebin.com/vGRJqPnG

**Comment by sylance** [comment]
Have the same issue.  20-30 seconds per pair no matter how many pairs are run, or changes made to Ticker Update or Bot Delay.  For me, I notice it is much more slower on Bittrex than Polo.  I'm running them side by side and Polo is faster even though Bot Delay for Polo is set to 10.

**Comment by paramecie** [comment]
It's new from 5.0.4 to 5.0.5, read here:
https://github.com/GuntharDeNiro/Gunthy/releases/tag/v505_95572df

New data servers for initial calculation of EMA and BB: Gunbot takes "close" history from gunthy servers at first start and then continues to collect datas from exchanges. This is adding capabilities to correctly calculate indicators since the first cycle: if you restart Gunbot, it doesnt need to collect data again

The server probably received an unexpected load. Here I simply can't use 5.0.5 for now.

**Comment by rhessing** [comment]
I would like to know if and/or when this issue could be expected to be fixed..
