### ISSUE TITLE
Error on strategy BB for XXBTZEUR on kraken while getting order book -| Error: FUCK KRAKEN

### ISSUE THREAD

**Issue by dangnm** [GuntharDeNiro/Gunthy#54]
Why does this issue always happen to me on 5.0.5.5 (Kraken)?
<img width="1072" alt="fck kraken issue" src="https://user-images.githubusercontent.com/5093683/31584864-2ed1e214-b1e1-11e7-98f0-9f5b32758ea3.png">

"Error on strategy BB for XXBTZEUR on kraken while getting order book -| Error: FUCK KRAKEN"

**Comment by paramecie** [comment]
LOL!!! That's one of the best error message I've ever seen.

Apart this, it may mean that many times (hence the "Fuck Kraken"), it doesn't give the appropriate information?

This gives you some background:
https://status.kraken.com/#
For now 2 months I follow it, it's still in "Degrade performance", it's a shame, and of course I wrote them.
Fuck Kraken, yes, that makes sense.

**Comment by dangnm** [comment]
@paramecie thank you so much! Finally there's the one answering my question. 1 more question. Does it mean that I can run the bot normally with that error message or it has to be solved before I can run the bot normally?

**Comment by paramecie** [comment]
This 5.0.5RC is still an alpha version...
I don't use it anymore because various problems, like the pairs cycle, etc.

It may be usable for a few pairs, and of course to learn how the whole thing works: the bot, the market, the trades, etc. In short, I wouldn't use it for production, but for education.
Good luck (but better than luck, learn a lot!)
;-)
